name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master

    - name: Make file
      run: make

    - name: Run check
      run: make check
